-- =====================================================
-- Sprint 69: ML Self-Tuning (Config-Driven)
-- =====================================================
-- Creates a learning layer that:
-- 1) Learns from S70 metrics and funnels
-- 2) Proposes tuning actions (config-level only)
-- 3) Applies changes only via S66 checkpoints
-- 4) Never rewrites code or models directly
-- =====================================================

-- =====================================================
-- 1. SCORING CONFIG TABLE
-- =====================================================
-- Stores configurable scoring model parameters
-- Changes here affect scoring without code changes

CREATE TABLE IF NOT EXISTS scoring_config (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Model identification
    model_name VARCHAR(100) NOT NULL,           -- e.g., 'qtle_v2', 'lead_priority'
    signal_key VARCHAR(100) NOT NULL,           -- e.g., 'revenue_signal', 'engagement_score'

    -- Config values
    weight DECIMAL(5,4) NOT NULL DEFAULT 1.0,   -- Signal weight in model
    threshold DECIMAL(10,4),                     -- Optional threshold for binary signals
    enabled BOOLEAN NOT NULL DEFAULT true,

    -- Vertical/Territory scope (NULL = global)
    vertical_slug VARCHAR(50),
    territory_id UUID,

    -- Versioning
    version INTEGER NOT NULL DEFAULT 1,

    -- Metadata
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),

    -- Constraints
    UNIQUE(model_name, signal_key, vertical_slug, territory_id, version)
);

CREATE INDEX idx_scoring_config_model ON scoring_config(model_name);
CREATE INDEX idx_scoring_config_vertical ON scoring_config(vertical_slug);
CREATE INDEX idx_scoring_config_lookup ON scoring_config(model_name, vertical_slug, territory_id, enabled);

-- =====================================================
-- 2. SCORING TUNING ACTIONS TABLE
-- =====================================================
-- Proposed tuning actions generated by ML analysis
-- Must be approved via S66 checkpoints before application

CREATE TABLE IF NOT EXISTS scoring_tuning_actions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Action details
    action_type VARCHAR(50) NOT NULL,           -- 'adjust_weight', 'adjust_threshold', 'toggle_signal', 'add_signal'
    target_model VARCHAR(100) NOT NULL,
    target_signal VARCHAR(100) NOT NULL,

    -- Value changes
    old_value JSONB,                            -- Current value before change
    new_value JSONB NOT NULL,                   -- Proposed new value

    -- Scope
    vertical_slug VARCHAR(50),
    territory_id UUID,

    -- Analysis backing
    confidence DECIMAL(5,4) NOT NULL,           -- 0.0 to 1.0
    evidence JSONB NOT NULL DEFAULT '{}',       -- Metrics/patterns supporting this action
    expected_impact JSONB,                       -- Predicted improvement

    -- Status tracking
    status VARCHAR(20) NOT NULL DEFAULT 'proposed',  -- proposed, approved, applied, rejected, expired

    -- S66 checkpoint reference
    checkpoint_id UUID,

    -- Audit trail
    proposed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by VARCHAR(100),
    applied_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- Constraints
    CHECK (status IN ('proposed', 'approved', 'applied', 'rejected', 'expired')),
    CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX idx_tuning_actions_status ON scoring_tuning_actions(status);
CREATE INDEX idx_tuning_actions_model ON scoring_tuning_actions(target_model);
CREATE INDEX idx_tuning_actions_vertical ON scoring_tuning_actions(vertical_slug);
CREATE INDEX idx_tuning_actions_proposed ON scoring_tuning_actions(proposed_at DESC);

-- =====================================================
-- 3. WIN/LOSS PATTERNS TABLE
-- =====================================================
-- Computed patterns from conversion funnels
-- Used to inform tuning suggestions

CREATE TABLE IF NOT EXISTS win_loss_patterns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Pattern dimensions
    segment_key VARCHAR(100) NOT NULL,          -- e.g., 'enterprise', 'smb', 'high_revenue'
    signal_key VARCHAR(100),                    -- Which signal correlates (optional)
    persona_key VARCHAR(100),                   -- Which persona used (optional)

    -- Scope
    vertical_slug VARCHAR(50) NOT NULL,
    territory_id UUID,

    -- Pattern metrics
    win_rate DECIMAL(5,4) NOT NULL,             -- Successful conversions / total
    loss_rate DECIMAL(5,4) NOT NULL,            -- Lost / total
    sample_size INTEGER NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,           -- Statistical confidence

    -- Supporting data
    avg_score_winners DECIMAL(10,4),
    avg_score_losers DECIMAL(10,4),
    top_signals JSONB,                          -- Array of most predictive signals

    -- Timing
    time_window_days INTEGER NOT NULL DEFAULT 30,
    last_computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    UNIQUE(segment_key, signal_key, persona_key, vertical_slug, territory_id),
    CHECK (win_rate >= 0 AND win_rate <= 1),
    CHECK (loss_rate >= 0 AND loss_rate <= 1),
    CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX idx_patterns_vertical ON win_loss_patterns(vertical_slug);
CREATE INDEX idx_patterns_segment ON win_loss_patterns(segment_key);
CREATE INDEX idx_patterns_computed ON win_loss_patterns(last_computed_at DESC);

-- =====================================================
-- 4. JOURNEY TUNING SUGGESTIONS TABLE
-- =====================================================
-- Optimization suggestions for journey steps
-- Based on performance metrics analysis

CREATE TABLE IF NOT EXISTS journey_tuning_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Journey targeting
    journey_id VARCHAR(100) NOT NULL,           -- Journey definition identifier
    step_id VARCHAR(100),                       -- Specific step (optional, NULL = journey-level)

    -- Scope
    vertical_slug VARCHAR(50),
    territory_id UUID,

    -- Current vs suggested
    current_config JSONB NOT NULL,              -- Current step/journey configuration
    suggested_change JSONB NOT NULL,            -- Proposed changes
    change_type VARCHAR(50) NOT NULL,           -- 'channel_switch', 'delay_adjust', 'followup_count', 'template_swap'

    -- Impact analysis
    impact_estimate JSONB NOT NULL,             -- { metric: estimated_improvement }
    confidence DECIMAL(5,4) NOT NULL,
    evidence JSONB NOT NULL DEFAULT '{}',       -- Performance data backing suggestion

    -- Status
    status VARCHAR(20) NOT NULL DEFAULT 'proposed',

    -- S66 checkpoint reference
    checkpoint_id UUID,

    -- Audit
    proposed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by VARCHAR(100),
    applied_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- Constraints
    CHECK (status IN ('proposed', 'approved', 'applied', 'rejected', 'expired')),
    CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX idx_journey_suggestions_journey ON journey_tuning_suggestions(journey_id);
CREATE INDEX idx_journey_suggestions_status ON journey_tuning_suggestions(status);
CREATE INDEX idx_journey_suggestions_vertical ON journey_tuning_suggestions(vertical_slug);

-- =====================================================
-- 5. PERSONA PERFORMANCE STATS TABLE
-- =====================================================
-- Aggregated performance metrics per persona
-- Used for persona ranking and selection

CREATE TABLE IF NOT EXISTS persona_performance_stats (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Persona identification
    persona_key VARCHAR(100) NOT NULL,          -- e.g., 'professional', 'casual', 'formal'

    -- Scope
    vertical_slug VARCHAR(50) NOT NULL,
    territory_id UUID,

    -- Performance metrics
    win_rate DECIMAL(5,4) NOT NULL DEFAULT 0,   -- Converted / contacted
    reply_rate DECIMAL(5,4) NOT NULL DEFAULT 0, -- Replied / sent
    open_rate DECIMAL(5,4) NOT NULL DEFAULT 0,  -- Opened / sent
    click_rate DECIMAL(5,4) NOT NULL DEFAULT 0, -- Clicked / opened

    -- Timing metrics
    avg_time_to_reply_hours DECIMAL(10,2),      -- Average hours to first reply
    avg_time_to_convert_hours DECIMAL(10,2),    -- Average hours to conversion

    -- Sample size
    sample_size INTEGER NOT NULL DEFAULT 0,

    -- Ranking
    rank_score DECIMAL(10,4),                   -- Computed ranking score
    rank_position INTEGER,                       -- Position within vertical/territory

    -- Timing
    time_window_days INTEGER NOT NULL DEFAULT 30,
    last_computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    UNIQUE(persona_key, vertical_slug, territory_id),
    CHECK (win_rate >= 0 AND win_rate <= 1),
    CHECK (reply_rate >= 0 AND reply_rate <= 1),
    CHECK (open_rate >= 0 AND open_rate <= 1),
    CHECK (click_rate >= 0 AND click_rate <= 1)
);

CREATE INDEX idx_persona_stats_vertical ON persona_performance_stats(vertical_slug);
CREATE INDEX idx_persona_stats_rank ON persona_performance_stats(vertical_slug, rank_position);
CREATE INDEX idx_persona_stats_persona ON persona_performance_stats(persona_key);

-- =====================================================
-- VIEWS
-- =====================================================

-- View: Pending tuning actions needing review
CREATE OR REPLACE VIEW v_pending_tuning_actions AS
SELECT
    id,
    action_type,
    target_model,
    target_signal,
    old_value,
    new_value,
    vertical_slug,
    confidence,
    expected_impact,
    proposed_at,
    EXTRACT(EPOCH FROM (NOW() - proposed_at)) / 3600 AS hours_pending
FROM scoring_tuning_actions
WHERE status = 'proposed'
ORDER BY confidence DESC, proposed_at ASC;

-- View: Best performing signals per model
CREATE OR REPLACE VIEW v_top_scoring_signals AS
SELECT
    sc.model_name,
    sc.signal_key,
    sc.weight,
    sc.vertical_slug,
    COALESCE(
        (SELECT AVG(wlp.win_rate)
         FROM win_loss_patterns wlp
         WHERE wlp.signal_key = sc.signal_key
         AND wlp.vertical_slug = sc.vertical_slug),
        0
    ) AS avg_win_rate,
    sc.enabled,
    sc.version
FROM scoring_config sc
WHERE sc.enabled = true
ORDER BY sc.model_name, sc.weight DESC;

-- View: Worst performing journeys (candidates for optimization)
CREATE OR REPLACE VIEW v_underperforming_journeys AS
SELECT
    journey_id,
    vertical_slug,
    COUNT(*) AS suggestion_count,
    AVG(confidence) AS avg_confidence,
    MAX(proposed_at) AS latest_suggestion
FROM journey_tuning_suggestions
WHERE status = 'proposed'
GROUP BY journey_id, vertical_slug
ORDER BY suggestion_count DESC, avg_confidence DESC;

-- View: Top personas per vertical
CREATE OR REPLACE VIEW v_top_personas AS
SELECT
    persona_key,
    vertical_slug,
    territory_id,
    win_rate,
    reply_rate,
    sample_size,
    rank_position,
    last_computed_at
FROM persona_performance_stats
WHERE sample_size >= 10  -- Minimum sample for statistical relevance
ORDER BY vertical_slug, rank_position ASC;

-- View: Recent pattern changes (for monitoring)
CREATE OR REPLACE VIEW v_recent_pattern_changes AS
SELECT
    segment_key,
    signal_key,
    vertical_slug,
    win_rate,
    loss_rate,
    sample_size,
    confidence,
    last_computed_at
FROM win_loss_patterns
WHERE last_computed_at > NOW() - INTERVAL '24 hours'
ORDER BY last_computed_at DESC;

-- =====================================================
-- FUNCTIONS
-- =====================================================

-- Function: Get active scoring config for a model
CREATE OR REPLACE FUNCTION get_scoring_config(
    p_model_name VARCHAR(100),
    p_vertical_slug VARCHAR(50) DEFAULT NULL,
    p_territory_id UUID DEFAULT NULL
)
RETURNS TABLE (
    signal_key VARCHAR(100),
    weight DECIMAL(5,4),
    threshold DECIMAL(10,4),
    enabled BOOLEAN,
    version INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT ON (sc.signal_key)
        sc.signal_key,
        sc.weight,
        sc.threshold,
        sc.enabled,
        sc.version
    FROM scoring_config sc
    WHERE sc.model_name = p_model_name
    AND sc.enabled = true
    AND (
        -- Territory-specific (highest priority)
        (sc.vertical_slug = p_vertical_slug AND sc.territory_id = p_territory_id)
        OR
        -- Vertical-specific (medium priority)
        (sc.vertical_slug = p_vertical_slug AND sc.territory_id IS NULL)
        OR
        -- Global (lowest priority)
        (sc.vertical_slug IS NULL AND sc.territory_id IS NULL)
    )
    ORDER BY sc.signal_key,
             sc.territory_id NULLS LAST,
             sc.vertical_slug NULLS LAST,
             sc.version DESC;
END;
$$ LANGUAGE plpgsql;

-- Function: Compute persona rank scores
CREATE OR REPLACE FUNCTION compute_persona_ranks(
    p_vertical_slug VARCHAR(50),
    p_territory_id UUID DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
    updated_count INTEGER;
BEGIN
    -- Calculate rank score: weighted combination of metrics
    -- win_rate (40%) + reply_rate (30%) + open_rate (20%) + click_rate (10%)
    UPDATE persona_performance_stats
    SET
        rank_score = (win_rate * 0.4) + (reply_rate * 0.3) + (open_rate * 0.2) + (click_rate * 0.1),
        last_computed_at = NOW()
    WHERE vertical_slug = p_vertical_slug
    AND (p_territory_id IS NULL OR territory_id = p_territory_id);

    GET DIAGNOSTICS updated_count = ROW_COUNT;

    -- Assign rank positions
    WITH ranked AS (
        SELECT
            id,
            ROW_NUMBER() OVER (
                PARTITION BY vertical_slug, territory_id
                ORDER BY rank_score DESC
            ) AS new_rank
        FROM persona_performance_stats
        WHERE vertical_slug = p_vertical_slug
        AND (p_territory_id IS NULL OR territory_id = p_territory_id)
    )
    UPDATE persona_performance_stats ps
    SET rank_position = r.new_rank
    FROM ranked r
    WHERE ps.id = r.id;

    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;

-- Function: Expire old proposed actions
CREATE OR REPLACE FUNCTION expire_old_tuning_actions(
    p_max_age_days INTEGER DEFAULT 7
)
RETURNS INTEGER AS $$
DECLARE
    expired_count INTEGER;
BEGIN
    UPDATE scoring_tuning_actions
    SET
        status = 'expired',
        reviewed_at = NOW(),
        rejection_reason = 'Auto-expired after ' || p_max_age_days || ' days'
    WHERE status = 'proposed'
    AND proposed_at < NOW() - (p_max_age_days || ' days')::INTERVAL;

    GET DIAGNOSTICS expired_count = ROW_COUNT;

    -- Also expire journey suggestions
    UPDATE journey_tuning_suggestions
    SET
        status = 'expired',
        reviewed_at = NOW(),
        rejection_reason = 'Auto-expired after ' || p_max_age_days || ' days'
    WHERE status = 'proposed'
    AND proposed_at < NOW() - (p_max_age_days || ' days')::INTERVAL;

    RETURN expired_count;
END;
$$ LANGUAGE plpgsql;

-- Function: Get tuning action summary
CREATE OR REPLACE FUNCTION get_tuning_summary(
    p_vertical_slug VARCHAR(50) DEFAULT NULL
)
RETURNS TABLE (
    action_type VARCHAR(50),
    status VARCHAR(20),
    count BIGINT,
    avg_confidence DECIMAL(5,4)
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        sta.action_type,
        sta.status,
        COUNT(*)::BIGINT,
        AVG(sta.confidence)::DECIMAL(5,4)
    FROM scoring_tuning_actions sta
    WHERE p_vertical_slug IS NULL OR sta.vertical_slug = p_vertical_slug
    GROUP BY sta.action_type, sta.status
    ORDER BY sta.action_type, sta.status;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- SEED DATA: Default scoring config
-- =====================================================

INSERT INTO scoring_config (model_name, signal_key, weight, description) VALUES
    ('qtle_v2', 'quality_score', 0.25, 'Data quality and completeness'),
    ('qtle_v2', 'timing_score', 0.25, 'Timing and recency signals'),
    ('qtle_v2', 'likelihood_score', 0.25, 'Conversion likelihood indicators'),
    ('qtle_v2', 'engagement_score', 0.25, 'Engagement and activity signals'),
    ('lead_priority', 'revenue_potential', 0.30, 'Estimated revenue potential'),
    ('lead_priority', 'fit_score', 0.25, 'ICP fit assessment'),
    ('lead_priority', 'intent_signals', 0.25, 'Buying intent indicators'),
    ('lead_priority', 'recency_score', 0.20, 'How recent the lead data is')
ON CONFLICT DO NOTHING;

-- =====================================================
-- COMMENTS
-- =====================================================

COMMENT ON TABLE scoring_config IS 'S69: Configurable scoring model parameters - changes affect scoring without code changes';
COMMENT ON TABLE scoring_tuning_actions IS 'S69: Proposed tuning actions from ML analysis - require S66 checkpoint approval';
COMMENT ON TABLE win_loss_patterns IS 'S69: Computed patterns from S70 conversion funnels';
COMMENT ON TABLE journey_tuning_suggestions IS 'S69: Journey optimization suggestions based on performance metrics';
COMMENT ON TABLE persona_performance_stats IS 'S69: Aggregated persona performance for ranking and selection';
