apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: upr-web-service
  labels:
    env: production
    team: upr
    cost-center: product
    component: web-service
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: projects/applied-algebra-474804-e6/locations/us-central1/connectors/upr-vpc-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cloudsql-instances: applied-algebra-474804-e6:us-central1:upr-postgres
        run.googleapis.com/cpu-throttling: 'true'
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/target-utilization-percentage: '60'
    spec:
      serviceAccountName: upr-runner@applied-algebra-474804-e6.iam.gserviceaccount.com
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/applied-algebra-474804-e6/upr-app-repo/upr-web-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL
              key: latest
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: REDIS_URL
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: JWT_SECRET
              key: latest
        - name: APOLLO_API_KEY
          valueFrom:
            secretKeyRef:
              name: APOLLO_API_KEY
              key: latest
        - name: SERPAPI_KEY
          valueFrom:
            secretKeyRef:
              name: SERPAPI_KEY
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: latest
        - name: NEVERBOUNCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: NEVERBOUNCE_API_KEY
              key: latest
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: TENANT_ID
              key: latest
        - name: UPR_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: UPR_ADMIN_USER
              key: latest
        - name: UPR_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: UPR_ADMIN_PASS
              key: latest
        - name: AGENT_HUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: AGENT_HUB_API_KEY
              key: latest
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
