-- scripts/20251007_add_learning_insights.sql
-- This script creates the table to store insights generated by the
-- reinforcement learning agent, which analyzes email performance.

BEGIN;

CREATE TABLE IF NOT EXISTS ai_learning_insights (
    id SERIAL PRIMARY KEY,
    -- The natural language summary of the high-performing pattern, generated by an LLM.
    -- e.g., "Opening lines that reference a specific company achievement have a 15% higher reply rate."
    insight_summary TEXT NOT NULL,
    
    -- An array of the outreach_generations IDs that were used as evidence to generate this insight.
    source_outreach_ids UUID[],

    -- Flag to control whether this insight is actively being used in new email generation prompts.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add an index to quickly find the latest active insights.
CREATE INDEX IF NOT EXISTS idx_active_insights_created_at ON ai_learning_insights (created_at DESC) WHERE is_active IS TRUE;


COMMIT;