#!/bin/bash
# GCP Cost Summary and Recommendations

PROJECT_ID="applied-algebra-474804-e6"
REGION="us-central1"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "           GCP COST OPTIMIZATION SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📊 CURRENT SITUATION (BEFORE optimization):"
echo ""
echo "Cloud Run Services (5 running 24/7):"
echo "  • upr-hiring-signals-worker: 4 CPU, 4GB  = ~$130/mo"
echo "  • upr-worker: 2 CPU, 4GB                 = ~$75/mo"
echo "  • upr-enrichment-worker: 2 CPU, 4GB      = ~$75/mo"
echo "  • upr-web-service: 2 CPU, 2GB            = ~$65/mo"
echo "  • coming-soon-service: 1 CPU, 512MB      = ~$25/mo"
echo "                                    SUBTOTAL: ~$370/mo"
echo ""
echo "Other Resources:"
echo "  • Redis (1GB BASIC, always on)           = ~$35/mo"
echo "  • VPC Connector (needed for DB access)   = ~$15/mo"
echo "  • Cloud SQL (currently STOPPED)          = ~$0/mo ✅"
echo "                                    SUBTOTAL: ~$50/mo"
echo ""
echo "TOTAL ESTIMATED MONTHLY COST: ~$420/month 😱"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "💰 AFTER OPTIMIZATION:"
echo ""
echo "Cloud Run Services (scale to zero, reduced resources):"
echo "  • upr-hiring-signals-worker: 1 CPU, 2GB, min=0  = ~$5/mo"
echo "  • upr-worker: 1 CPU, 2GB, min=0                 = ~$5/mo"
echo "  • upr-enrichment-worker: 1 CPU, 2GB, min=0      = ~$5/mo"
echo "  • upr-web-service: 1 CPU, 1GB, min=0            = ~$5/mo"
echo "  • coming-soon-service: 1 CPU, 512MB, min=0      = ~$3/mo"
echo "                                         SUBTOTAL: ~$23/mo"
echo ""
echo "Other Resources:"
echo "  • Redis (if kept)                                = ~$35/mo"
echo "  • Redis (if deleted)                             = ~$0/mo ✅"
echo "  • VPC Connector                                  = ~$15/mo"
echo "  • Cloud SQL (STOPPED)                            = ~$0/mo ✅"
echo "                                         SUBTOTAL: ~$15-50/mo"
echo ""
echo "NEW ESTIMATED MONTHLY COST: ~$38-73/month"
echo ""
echo "💵 TOTAL SAVINGS: ~$347-382/month (83-91% reduction!)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 ACTION PLAN:"
echo ""
echo "STEP 1 (CRITICAL - Do this NOW):"
echo "  Run: ./scripts/emergency-fix-all-services.sh"
echo "  Savings: ~$300-350/month"
echo "  Time: 2-3 minutes"
echo ""
echo "STEP 2 (Recommended):"
echo "  Run: ./scripts/optimize-redis.sh"
echo "  Review if you need Redis, delete if not"
echo "  Additional savings: ~$35/month"
echo ""
echo "STEP 3 (Monitor):"
echo "  Wait 24-48 hours and check billing:"
echo "  https://console.cloud.google.com/billing"
echo ""
echo "STEP 4 (Optional - VPC Connector):"
echo "  If you don't need private DB access, you could delete"
echo "  the VPC connector for another ~$15/month savings"
echo "  (But Cloud SQL is already stopped, so this may not apply)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ QUICK START:"
echo ""
echo "  cd /Users/skc/DataScience/upr"
echo "  ./scripts/emergency-fix-all-services.sh"
echo ""
echo "This will immediately stop the money burn! 🔥"
