/**
 * Sealed Context Envelope Types (PRD v1.2 §2)
 *
 * Every SIVA invocation MUST receive a sealed, versioned context envelope
 * generated by UPR-OS. SIVA cannot run without it.
 *
 * This envelope is the single strongest anti-clone moat.
 */

/**
 * @typedef {Object} SealedContextEnvelope
 * @property {string} envelope_version - Envelope schema version (e.g., "1.2.0")
 * @property {string} tenant_id - Tenant identifier
 * @property {string} user_id - User identifier
 * @property {string} persona_id - Canonical persona (1-7 per PRD §3.2)
 * @property {string} vertical - Vertical (e.g., "banking")
 * @property {string} sub_vertical - Sub-vertical (e.g., "employee_banking")
 * @property {string} region - Region code (e.g., "UAE")
 * @property {string[]} allowed_intents - List of allowed SIVA intents
 * @property {string[]} forbidden_outputs - List of forbidden output types
 * @property {string[]} allowed_tools - List of allowed SIVA tools
 * @property {EvidenceScope} evidence_scope - Evidence visibility settings
 * @property {MemoryScope} memory_scope - Memory depth settings
 * @property {CostBudget} cost_budget - Cost limits for this interaction
 * @property {LatencyBudget} latency_budget - Latency limits for this interaction
 * @property {EscalationRules} escalation_rules - Escalation thresholds
 * @property {DisclaimerRules} disclaimer_rules - Disclaimer requirements
 * @property {string} timestamp - ISO 8601 timestamp of envelope creation
 * @property {string} sha256_hash - SHA256 hash of envelope contents (excluding this field)
 */

/**
 * @typedef {Object} EvidenceScope
 * @property {boolean} show_raw_evidence - Whether to show raw evidence
 * @property {boolean} show_provenance - Whether to show provenance DAG
 * @property {number} max_evidence_age_days - Maximum evidence age
 * @property {string[]} allowed_sources - Allowed evidence sources
 */

/**
 * @typedef {Object} MemoryScope
 * @property {number} max_days - Maximum memory depth in days
 * @property {boolean} stateless - Force stateless mode (WhatsApp)
 * @property {boolean} summarized_only - Only use summarized memory
 */

/**
 * @typedef {Object} CostBudget
 * @property {number} max_tokens - Maximum tokens for this call
 * @property {number} max_cost_usd - Maximum cost in USD
 * @property {string} model_tier - Model tier (cheap, standard, deep)
 */

/**
 * @typedef {Object} LatencyBudget
 * @property {number} p95_ms - P95 latency target in ms
 * @property {number} timeout_ms - Hard timeout in ms
 */

/**
 * @typedef {Object} EscalationRules
 * @property {number} disclaimer_threshold - Risk threshold for disclaimer (0.3)
 * @property {number} escalation_threshold - Risk threshold for escalation (0.7)
 * @property {number} block_threshold - Risk threshold for blocking (0.9)
 * @property {string} escalation_target - Target for escalation (queue, supervisor, etc.)
 */

/**
 * @typedef {Object} DisclaimerRules
 * @property {string[]} required_topics - Topics requiring disclaimer
 * @property {string} disclaimer_template - Template for disclaimers
 */

// Canonical Personas per PRD §3.2
export const CANONICAL_PERSONAS = {
  CUSTOMER_FACING: '1', // WhatsApp / Email - Most restricted
  SALES_REP: '2',       // SaaS UI - Standard intelligence
  SUPERVISOR: '3',      // Approves escalations
  ADMIN: '4',           // Admin / Settings
  COMPLIANCE: '5',      // Compliance / Audit
  INTEGRATION: '6',     // Integration / API
  INTERNAL: '7',        // Internal users (same as SALES_REP, tenant-level constraints)
};

// NOTE: No "demo mode" or "sandbox" persona. Production Shadow Tenant uses
// real personas with tenant-level constraints (data boundary, spend caps).
// See: docs/SHADOW_TENANT.md

// Persona capability profiles per PRD §4
export const PERSONA_CAPABILITIES = {
  '1': { // Customer-Facing
    allowed_intents: ['general_faq', 'ask_clarifying', 'trigger_escalation'],
    forbidden_outputs: ['raw_evidence', 'lead_scoring', 'draft_outreach', 'rates_approvals'],
    max_tokens: 1000,
    max_cost_usd: 0.01,
    model_tier: 'cheap',
    memory_days: 0,
    stateless: true,
  },
  '2': { // Sales-Rep
    allowed_intents: ['general_faq', 'ask_clarifying', 'collect_company_salary', 'provide_checklist', 'explain_opportunity', 'draft_outreach', 'lead_scoring', 'show_evidence', 'trigger_escalation'],
    forbidden_outputs: ['rates_approvals_ungated'],
    max_tokens: 4000,
    max_cost_usd: 0.10,
    model_tier: 'deep',
    memory_days: 7,
    stateless: false,
  },
  '3': { // Supervisor
    allowed_intents: ['general_faq', 'explain_opportunity', 'lead_scoring', 'show_evidence', 'trigger_escalation'],
    forbidden_outputs: ['draft_outreach', 'discovery_enrich'],
    max_tokens: 4000,
    max_cost_usd: 0.10,
    model_tier: 'deep',
    memory_days: 30,
    stateless: false,
  },
  '4': { // Admin
    allowed_intents: ['general_faq', 'ask_clarifying'],
    forbidden_outputs: ['lead_scoring', 'show_evidence', 'discovery_enrich', 'draft_outreach'],
    max_tokens: 2000,
    max_cost_usd: 0.05,
    model_tier: 'standard',
    memory_days: 7,
    stateless: false,
  },
  '5': { // Compliance
    allowed_intents: ['general_faq', 'explain_opportunity', 'show_evidence'],
    forbidden_outputs: ['draft_outreach', 'discovery_enrich', 'rates_approvals'],
    max_tokens: 4000,
    max_cost_usd: 0.10,
    model_tier: 'deep',
    memory_days: 90,
    stateless: false,
  },
  '6': { // Integration / API
    allowed_intents: ['lead_scoring', 'show_evidence'],
    forbidden_outputs: ['draft_outreach', 'rates_approvals', 'trigger_escalation'],
    max_tokens: 2000,
    max_cost_usd: 0.05,
    model_tier: 'standard',
    memory_days: 0,
    stateless: true,
  },
  '7': { // Internal (same as SALES_REP, tenant-level constraints apply)
    allowed_intents: ['general_faq', 'ask_clarifying', 'collect_company_salary', 'provide_checklist', 'explain_opportunity', 'draft_outreach', 'lead_scoring', 'show_evidence', 'trigger_escalation'],
    forbidden_outputs: ['rates_approvals_ungated'],
    max_tokens: 4000,
    max_cost_usd: 0.10,
    model_tier: 'deep',
    memory_days: 7,
    stateless: false,
    // NOTE: No synthetic_only flag. Shadow Tenant constraints are enforced at tenant level, not persona level.
  },
};

// Current envelope version
export const ENVELOPE_VERSION = '1.2.0';

// Default escalation rules per PRD §5.1
export const DEFAULT_ESCALATION_RULES = {
  disclaimer_threshold: 0.3,  // Risk >= 0.3 -> Disclaimer required
  escalation_threshold: 0.7,  // Risk >= 0.7 -> Mandatory human escalation
  block_threshold: 0.9,       // Risk >= 0.9 -> Response blocked
  escalation_target: 'supervisor_queue',
};

export default {
  CANONICAL_PERSONAS,
  PERSONA_CAPABILITIES,
  ENVELOPE_VERSION,
  DEFAULT_ESCALATION_RULES,
};
