apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: upr-os-worker
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/description: "UPR OS Unified Worker - Async pipeline processing"
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 900
      containers:
        - image: gcr.io/upr-sales-intelligence/upr-os-worker:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: NODE_ENV
              value: production
            - name: WORKER_TYPE
              value: unified
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-credentials
                  key: api-key
            - name: APOLLO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apollo-credentials
                  key: api-key
            - name: PUBSUB_TOPIC
              value: upr-os-jobs
            - name: PUBSUB_SUBSCRIPTION
              value: upr-os-worker-sub
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
